blueprint:
  name: CheckWatt Monthly
  description: create a monthly average entity
  domain: automation
  ### fo get the daily sensor
  input:
    daily_sensor:
      name: CheckWatt daily revenue sensor
      selector:
        entity:
          filter:
            integration: checkwatt
            device_class: monetary
    monthly_sensor:
      name: CheckWatt monthly revenue sensor
      selector:
        entity:
          filter:
            domain: input_number

action:
  service: input_number.set_value
  data_template:
    value: >-
    {{ states('!input monthly_sensor') | float +
    states('!input daily') | float }}
  target:
    entity_id: !input monthly_sensor
mode: single
