blueprint:
  name: CheckWatt monthly
  description: create a monthly average entity
  domain: automation
  input:
    device:
      filter:
      - integration: checkwatt
        manufacturer: checkwatt
