blueprint:
  name: Motion Light Tutorial
  description: Turn a light on based on detected motion
  domain: automation
  input:
    device:
      filter:
      - integration: checkwatt
        manufacturer: checkwatt
      entity:
      - domain: sensor
