blueprint:
  name: Motion Light Tutorial
  description: Turn a light on based on detected motion
  domain: automation
  input:
    remote:
      name: Monthl
      description: CW monthly
      selector:
        device:
          integration: checkwatt
          manufacturer: checkwatt
          multiple: false
