blueprint:
  name: CheckWatt Monthly
  description: creates a monthly revenue entity
  domain: automation
  input:
    daily_sensor:
      name: CheckWatt daily revenue sensor
      selector:
        entity:
          filter:
            integration: checkwatt
            device_class: monetary
    monthly_sensor:
      name: CheckWatt monthly revenue sensor
      selector:
        entity:
          filter:
            domain: input_number
trigger:
  platform: time
  at: "23:59:50"
condition:
  - condition: template
    value_template: "value_template: \"{{ now().day == 1 }}\""
    
action:
  service: input_number.set_value
  data_template:
    value: "value_template: \"{{ (!input monthly_sensornow | float) + (!input daily_sensor | float) }}\""
  target:
    entity_id: !input monthly_sensor
mode: single
