blueprint:
  name: CheckWatt monthly3
  description: create a monthly average entity
  domain: automation
  ### fo get the daily sensor
  input:
    daily_sensor:
      name: CheckWatt daily revenue sensor
      selector:
        entity:
          filter:
            integration: checkwatt
            device_class: monetary
  sensors:
    basedoninput:
      friendly_name: 'Based On Input'
      value_template: >-
      {{ (states('sensor.lgf_active_power_import')) }}

  trigger:
    platform: time
    at: "00:00:01"
  condition:
    - condition: template
      value_template: "value_template: \"{{ now().day == 1 }}\""
  action:
    - service: number.set_value
      data: {}
  mode: single
