blueprint:
  name: CheckWatt monthly
  description: create a monthly average entity
  domain: automation
  input:
    door_sensor:
      name: door sens
      selector:
        entity:
          filter:
            - integration: checkwatt
