blueprint:
  name: CheckWatt Monthly
  description: creates an automation to update monthly revenue entity
  domain: automation
  input:
    daily_sensor:
      name: CheckWatt daily revenue sensor
      selector:
        entity:
          filter:
            integration: checkwatt
            device_class: monetary
    monthly_sensor:
      name: CheckWatt monthly revenue sensor
      selector:
        entity:
          filter:
            domain: input_number
trigger:
  platform: time
  at: "18:45:00"


variables:
  month: !input monthly_sensor
  day: !input daily_sensor
  
action:
  service: input_number.set_value
  data_template:
    value: "value_template: \"{{ month | float + day | float }}\""
  target:
    entity_id: !input monthly_sensor
mode: single
